- name: Check Jenkins server
  debug:
    msg: "Check the Jenkins server: http://{{ inventory_hostname }}:8080"

- name: Wait for Jenkins to start
  uri:
    url: "{{ jenkins_url }}"  # URL of Jenkins
    status_code: 200
    timeout: 60
  register: jenkins_response
  until: jenkins_response.status == 200
  retries: 10
  delay: 10

#- name: add nodes
#  community.docker.docker_container_exec:
#    container: "{{ docker_container }}"
