---
- name: Check if Jenkins user exists
  shell: getent passwd {{ jenkins_user }}
  ignore_errors: yes
  register: jenkins_user_check

- name: Create Jenkins User
  user:
    name: "{{ jenkins_user }}"
    uid: 1000
    gid: 1000
    home: "{{ jenkins_home_dir }}"
    home_mode: "u+rwx,g+rwx"
    createhome: yes
    shell: "/bin/bash"
  when: jenkins_user_check.rc != 0

