---
- name: Jenkins Master role is being executed
  debug:
    msg: "Jenkins Master is going to be containirized!"  

- block:
    - include_tasks: jenkins_user.yml
  tags: user_ssh

- block:
    - name: Install docker engine on Jenkins master
      include_tasks: install_docker.yml
  tags: install_packages

# Prepare the jenkins master
- name: Prepare Jenkins master for containers
  include_tasks: prepare_master.yml

# Create and run Jenkins in container
- block:
    - name: Create and run Jenkins master in container
      include_tasks: jenkins_dockerized.yml
  tags: dockerized   

- name: Perform action to setup the new Jenkins server
  debug:
    msg: "Setup the new Jenkins server"

- name: Configure jenkins
  include_tasks: jenkins_config.yml
  vars:
    jenkins_url: "http://{{ inventory_hostname }}:8080"

# Check for .ssh and ssh keys
- block:
    - name: Check and create if not exist .ssh and keys
      include_tasks: conf_ssh.yml
  tags: user_ssh 

# Copy Jenkins config files to ansible host 
- block:
    - name: Check and create if not exist .ssh and keys
      include_tasks: backup_config.yml
  tags: backup 

#- name: Start docker-compose
#  docker_compose:
#  project_src: "{{remote_dir}}/jenkins_master_docker.yml"
#  state: started

# Run 'healthcheck' to check the Jenkins container status
- block:
    - include_tasks: healthcheck.yml
  tags: healthcheck

- name: Clear gathered facts
  meta: clear_facts
