galaxy_info:
  author: Velislav Kolev
  description: Role for installing and configuring Jenkins slave.
  license: MIT
  min_ansible_version: 2.10
  platforms:
    - name: Ubuntu
      versions:
        - all
    - name: CentOS
      versions:
        - all
  galaxy_tags:
    - jenkins
    - slave