packages_to_install:
  Debian:
    - apt-transport-https
    - ca-certificates
    - curl
    - software-properties-common
    - python3-pip
    - virtualenv
    - python3-setuptools   
  RedHat:
    - 'yum-utils'
    - 'device-mapper-persistent-data'
    - 'lvm2'
jenkins_user: jenkins
jenkins_pass: admin
jenkins_home_dir: /home/jenkins
jenkins_config_file_path: "{{ jenkins_home_dir }}/config.xml"
jenkins_master_url: "{{ master01 }}:8080"
#jenkins_url: "http://{{ jenkins_master_url }}"
# === variables for agents
jenkins_agent_dir: /home/jenkins
jenkins_slave_user: "{{jenkins_user}}"
jenkins_slave_user_ssh_key: "{{ jenkins_home_dir }}/.ssh/id_rsa_jenkins"
node_names:
  - agent01
  - agent02
nodeRemoteFS: "{{ jenkins_agent_dir }}/jenkins-agent"
node_numExecutors: 6
nodePort: 22
node_mode: NORMAL # or EXCLUSIVE
# === docker file variables
plugin_file: "plugins.txt"
remote_dir: /opt/containers/jenkins
jenkins_data: "{{remote_dir}}/data"
base_image: jenkins/jenkins:lts
docker_container: itops_jenkins
docker_image: jenkins_img
image_tag: test
jenkins_agent_port: 50000
