---
- name: Add group "jenkins" to remote node
  group:
    name: "{{ jenkins_user }}"
    gid: 1000
    state: present
    
- name: Create Jenkins User and add it to groups
  become: yes
  user:
    name: "{{ jenkins_user }}"
    uid: 1000
    group: "{{ jenkins_user }}"
    home: "{{ jenkins_home_dir }}"
    createhome: true
    shell: "/bin/bash"
