FROM {{ base_image }}

ENV JENKINS_USER {{ jenkins_user }}
ENV JENKINS_PASS {{ jenkins_pass }}
ENV JENKINS_SLAVE_AGENT_PORT {{ jenkins_agent_port }}

ENV JAVA_OPTS="-Xmx4096m"
ENV JAVA_OPTS -Djenkins.install.runSetupWizard=false
#ENV JENKINS_OPTS="--logfile=/var/jenkins_home/jenkins-master.log"

COPY --chown=$JENKINS_USER:$JENKINS_USER {{ plugin_file }} /tmp/plugins.txt
RUN jenkins-plugin-cli -f /tmp/plugins.txt
RUN echo 2.7.1 > /usr/share/jenkins/ref/jenkins.install.UpgradeWizard.state
RUN echo 2.7.1 > /usr/share/jenkins/ref/jenkins.install.InstallUtil.lastExecVersion

COPY --chown=$JENKINS_USER:$JENKINS_USER scripts/*.groovy /usr/share/jenkins/ref/init.groovy.d/
#COPY --chown=$JENKINS_USER:$JENKINS_USER scripts/unlock_jenkins.groovy /usr/share/jenkins/ref/init.groovy.d/
#COPY --chown=$JENKINS_USER:$JENKINS_USER scripts/add_jenkins_user.groovy /usr/share/jenkins/ref/init.groovy.d/
#COPY --chown=$JENKINS_USER:$JENKINS_USER scripts/executors.groovy /usr/share/jenkins/ref/init.groovy.d/
#COPY --chown=$JENKINS_USER:$JENKINS_USER scripts/add_agent01.groovy /usr/share/jenkins/ref/init.groovy.d/
#COPY --chown=$JENKINS_USER:$JENKINS_USER scripts/add_agent02.groovy /usr/share/jenkins/ref/init.groovy.d/